name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Go Build
      run: go build -v ./...

    - name: Go Test
      run: go test -v ./...

    - name: Goxc Install
      run: go get github.com/laher/goxc

    - name: Goxc Build
      run: export GOPATH=$(go env GOPATH) && make build

    - name: Goxc Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: gox-build-output
        path: build
